[package]
name = "fetch-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
rust-crypto = "0.2.36"
serde_json = "1.0.91"

